# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argus < Formula
  desc "AI-powered observability CLI for SREs"
  homepage "https://github.com/lbarahona/argus"
  version "0.5.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lbarahona/argus/releases/download/v0.5.2/argus_0.5.2_darwin_amd64.tar.gz"
      sha256 "c54065a6aceaef8ee1615d08ebe3c0c1e7338498a547fc08388a598ed1264c39"

      define_method(:install) do
        bin.install "argus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lbarahona/argus/releases/download/v0.5.2/argus_0.5.2_darwin_arm64.tar.gz"
      sha256 "35a372426e2bf68c70cfc43c7043e7bef09fa875e50d4cb89024cdf6ddfb07c0"

      define_method(:install) do
        bin.install "argus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lbarahona/argus/releases/download/v0.5.2/argus_0.5.2_linux_amd64.tar.gz"
      sha256 "1dc9ef23b2adf4da959381d9bec02068693a17e837cbca9e63389130f053edfe"
      define_method(:install) do
        bin.install "argus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lbarahona/argus/releases/download/v0.5.2/argus_0.5.2_linux_arm64.tar.gz"
      sha256 "486f4f422298c6f2e06b984246a9bf10484031358347257414cf92ad3a12b3fc"
      define_method(:install) do
        bin.install "argus"
      end
    end
  end

  test do
    assert_match "argus", shell_output("#{bin}/argus version 2>&1", 0)
  end
end
