# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argus < Formula
  desc "AI-powered observability CLI for SREs"
  homepage "https://github.com/lbarahona/argus"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lbarahona/argus/releases/download/v0.5.0/argus_0.5.0_darwin_amd64.tar.gz"
      sha256 "7d8c053b78dcd1368f1049a01e1012fc14e147404d6831600b2150dbcbb133c2"

      define_method(:install) do
        bin.install "argus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lbarahona/argus/releases/download/v0.5.0/argus_0.5.0_darwin_arm64.tar.gz"
      sha256 "26901f672f4bac498b168cd0c8070a2c4f45a2b30bdb750af040a3aaf612b3ea"

      define_method(:install) do
        bin.install "argus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lbarahona/argus/releases/download/v0.5.0/argus_0.5.0_linux_amd64.tar.gz"
      sha256 "56462c87363bc36f1a6a09e97ccdf44a24a1afead9ddda062fb295ecb82b2794"
      define_method(:install) do
        bin.install "argus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lbarahona/argus/releases/download/v0.5.0/argus_0.5.0_linux_arm64.tar.gz"
      sha256 "6c2d5075dbdbf2ed84bc43002373e59aa159f21ed8b5a99f110c8b7f465b45f2"
      define_method(:install) do
        bin.install "argus"
      end
    end
  end

  test do
    assert_match "argus", shell_output("#{bin}/argus version 2>&1", 0)
  end
end
