# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Argus < Formula
  desc "AI-powered observability CLI for SREs"
  homepage "https://github.com/lbarahona/argus"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lbarahona/argus/releases/download/v0.6.0/argus_0.6.0_darwin_amd64.tar.gz"
      sha256 "d1c72afc54ba6034bed8573c619a821c43896bc88d1dd3745879b65e3718773e"

      define_method(:install) do
        bin.install "argus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lbarahona/argus/releases/download/v0.6.0/argus_0.6.0_darwin_arm64.tar.gz"
      sha256 "9c37c95138c2330b2b9a540bb1f4ee53f2bbae24f8efe3144c1a1785938b1be5"

      define_method(:install) do
        bin.install "argus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lbarahona/argus/releases/download/v0.6.0/argus_0.6.0_linux_amd64.tar.gz"
      sha256 "d2bcc9150fe59f64571ee91245b2801e5d580025469a07796a9ff3e059a27033"
      define_method(:install) do
        bin.install "argus"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lbarahona/argus/releases/download/v0.6.0/argus_0.6.0_linux_arm64.tar.gz"
      sha256 "808d08ebb2bd45b53079c759b2860f717831db35dfe20c245fb854f6bb344904"
      define_method(:install) do
        bin.install "argus"
      end
    end
  end

  test do
    assert_match "argus", shell_output("#{bin}/argus version 2>&1", 0)
  end
end
